name: First Practice of Github Actions

env:
  APPLICATION_NAME: Glepka
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}" 

on: 
  push:
    branches: main
    
jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo "Hello, World from Testing"
      - name: Execute few commands
        run: | 
          echo "Hello msg1!"
          echo "Hello msg2!"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      
  my-deploy:
    needs: [my-testing]
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, World from Deploy"
    - name: Deployment package
      run: |
        echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
